server:
  port: 8080

spring:
  datasource:
    jpa-config:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://ip:port/db_name
      username: username
      password: password
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 8192MB
      max-request-size: 8192MB
      location: E:\\file\\
